//@GeneratedCode
namespace QTHungryDogsCustomer.WebApi
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
        }
    }
}
