//@GeneratedCode
namespace QTHungryDogsCustomer.AspMvc
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
            builder.Services.AddTransient<QTHungryDogsCustomer.Logic.Contracts.Base.IRestaurantsService<QTHungryDogsCustomer.Logic.ServiceModels.Base.Restaurant>, QTHungryDogsCustomer.Logic.Services.Base.RestaurantsService>();
        }
    }
}
