//@GeneratedCode
namespace QTHungryDogsCustomer.Logic.Contracts.Base
{
    ///
    /// Generated by the generator
    ///
    public partial interface IRestaurantsService<T> : Contracts.IBaseAccess<T>
    {
    }
}
